# -*- coding: utf-8 -*-
"""EXP 1-6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AOcTKrdlvT2JmqJmtVXANIS9SYsP7B9O
"""

import numpy as np

student_scores = np.array([
    [80, 75, 85, 70],
    [90, 80, 88, 75],
    [70, 85, 80, 65],
    [85, 90, 82, 80]
])

subject_avg = np.mean(student_scores, axis=0)

subjects = ["Math", "Science", "English", "History"]

print("Subject averages:", subject_avg)

highest = np.argmax(subject_avg)
print("Highest average subject:", subjects[highest])

import numpy as np

sales_data = np.array([
    [100, 120, 150],
    [200, 180, 220],
    [80, 90, 100]
])

average_price = np.mean(sales_data)

print("Average price:", average_price)

import numpy as np

house_data = np.array([
    [3, 1500, 250000],
    [5, 2200, 400000],
    [4, 1800, 300000],
    [6, 2500, 500000],
    [5, 2100, 450000]
])

selected = house_data[house_data[:, 0] > 4]

average_price = np.mean(selected[:, 2])

print("Average sale price:", average_price)

import numpy as np

sales_data = np.array([100000, 120000, 130000, 150000])


total_sales = np.sum(sales_data)


percentage_increase = ((sales_data[3] - sales_data[0])
                       / sales_data[0]) * 100

print("Total sales:", total_sales)
print("Percentage increase:", percentage_increase, "%")

import numpy as np

fuel_efficiency = np.array([30, 35, 40, 45, 50])


average = np.mean(fuel_efficiency)

model1 = fuel_efficiency[0]
model2 = fuel_efficiency[1]

improvement = ((model2 - model1) / model1) * 100

print("Average fuel efficiency:", average, "MPG")
print("Percentage improvement:", improvement, "%")

import numpy as np

prices = np.array([100, 200, 150])
quantities = np.array([2, 1, 3])

discount_rate = 10
tax_rate = 5

subtotal = np.sum(prices * quantities)

discount = subtotal * discount_rate / 100

discounted_price = subtotal - discount

tax = discounted_price * tax_rate / 100

total_cost = discounted_price + tax

print("Subtotal:", subtotal)
print("Discount:", discount)
print("Tax:", tax)
print("Total cost:", total_cost)